/**
 * Represents a chat message in the application's chat system.
 *
 * This type defines the structure for messages that are exchanged between
 * the server and client components. It serves as the canonical message format
 * for the chat feature, ensuring type safety across the application.
 *
 * @interface ChatMessage
 * @property {string} id - Unique identifier for the message, typically from the database
 * @property {'user' | 'assistant' | 'developer'} role - The sender/source of the message:
 *   - 'user': Messages sent by the human user
 *   - 'assistant': Messages generated by the AI assistant
 *   - 'developer': System messages or developer notes (mapped to 'system' in AI SDK)
 * @property {string} content - The actual text content of the message
 * @property {string} createdAt - ISO timestamp string indicating when the message was created
 *
 * @example
 * ```typescript
 * const message: ChatMessage = {
 *   id: '123e4567-e89b-12d3-a456-426614174000',
 *   role: 'user',
 *   content: 'Hello, how can you help me today?',
 *   createdAt: '2024-01-15T10:30:00.000Z'
 * };
 * ```
 *
 * @see {@link ChatInterface} - Component that renders these messages
 * @see {@link getThreadWithMessages} - Service function that returns messages in this format
 */
export type ChatMessage = {
  id: string;
  role: 'user' | 'assistant' | 'developer';
  content: string;
  createdAt: string;
};
